DATALOADING: CUSTOM
DATA_FILE_PATH: XAUUSD15.csv
FIXED_LOT_SIZE: 0.02
MODE: LIVE
PATHS:
  LOG_FILE: system.log
  RESULTS_DIR: results
  STATE_FILE: trade_state.pkl
RISK_MANAGEMENT: DYNAMIC
RISK_PERCENTAGE: 1.0
STRATEGY_PARAMS:
  SL_PIPS: 100
  TP_PIPS: 200
  TRAIL_DIST_PIPS: 5
  TRAIL_TRIGGER_PIPS: 20
TIMEFRAME: M15
TIMEZONE:
  BROKER: Europe/Athens
  USER: Asia/Kolkata
TRADING_SESSION:
  ASIAN_END: '13:30'
  ASIAN_START: 03:30
  TRADE_END: '21:30'
